config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :channels do
    resource :channel_user
    resources :messages
  end
  devise_for :users
  ActiveAdmin.routes(self)
  root 'movies#index'
  resources :movies, only: %i[index show] do
    resources :reviews
    member do
      put 'like' => 'movies#upvote'
      put 'dislike' => 'movies#downvote'
    end
  end
  get 'favorite/:id' => 'favorites#show', as: 'favorite'
  delete 'favorite/:id' => 'favorites#destroy'
  post 'line_items' => 'line_items#create'
  get 'line_items/:id' => 'line_items#show', as: 'line_item'
  delete 'line_items/:id' => 'line_items#destroy'
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :channel_users, dependent: :destroy
  has_many :users, through: :channel_users
  has_many :messages, dependent: :destroy
  belongs_to :author, class_name: 'User', foreign_key: :user_id

  validates :name, presence: true, length: { maximum: 18 }, uniqueness: true
  validates :author, presence: true
  validate :author_channel_count

  def author_channel_count
    errors.add(:name, 'Не больше 6 созданных каналов на пользователя.') if author.channel_author.count > 6
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_channel, only: %i[show edit update destroy]

  # GET /channels
  # GET /channels.json
  def index
    if params[:search].present?
      search = params[:search]
      @channels = Channel.where('name LIKE ? OR name LIKE ?', "%#{search.capitalize}%",
                                "%#{search.downcase}%")
    else
      @channels = Channel.all
    end
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    @channels = Channel.all
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit; end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(channel_params)
    @channel.author = current_user
    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Канал успешно создан.' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Канал успешно изменён.' }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: 'Канал успешно удалён.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_channel
    @channel = Channel.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def channel_params
    params.require(:channel).permit(:name)
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.erb
<%= form_for(@channel) do |f| %>
	<% unless @channel.errors.empty? %>
		<div id="error_explanation">
			<h2> Исправьте ошибку </h2>
			<ul>
			  <% @channel.errors.full_messages.each do |msg| %>
			    <li><%= msg %></li>
			</ul>
		  <% end %>
		</div>
	<% end %>
	<div class="form-group">
		<%= f.label :name %>
  	<%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.submit "Создать", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Изменить канал</h1>

<%= render 'form', channel: @channel %>

<%= link_to 'Смотреть', @channel %> |
<%= link_to 'Назад', channels_path %>

app/views/channels/index.html.erb
<div class="container">
  <div class="row">
    <h2 class="channel-index-title">Каналы</h2>
    <%= form_tag channels_path, method: :get, class: 'form-inline my-2 my-md-0' do %>
    <p>
      <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search" %>
    </p>
  <% end %>
  </div>
</div>


<div class="container channel-index">
  <% @channels.each do |channel| %>
    <div class="row">
        <p><%= link_to channel.name, channel, class: "channel-index-link"%></p> <small><i> Автор: <%= channel.author.username %></i></small>
        <% if channel.author == current_user %>
          <p><%= link_to "изменить", edit_channel_path(channel), class: "p-author-link" %></p>
          <p><%= link_to "удалить", channel_path(channel), method: :delete, class: "p-author-link" %></p>
        <% end %>
    </div>
  <% end %>
</div>
<hr>
<%= link_to 'Новый канал', new_channel_path %>

app/views/channels/new.html.erb
<h1>Новый канал</h1>

<%= render 'form', channel: @channel %>

<%= link_to 'Назад', channels_path %>

app/views/channels/show.html.erb
<div class="row">
		<div class="col-sm-2 border-right">
			<div class="d-flex justify-content-between">
				<h5>Каналы</h5>
				<%= link_to "", new_channel_path, class: "fa fa-plus" %>
			</div>
			<% @channels.each do |channel| %>
				<div>
					<%= link_to channel.name, channel %>
					<% if current_user.channels.include?(channel) %>
						<%= link_to "", channel_channel_user_path(channel), class: "fa fa-trash", method: :delete %>
					<% end %>
				</div>
			<% end %>
			<hr class="hr-chat"/>


			<div class="d-flex justify-content-between">
				<h5>Пользователи</h5>
			</div>
			<% @channel.users.each do |user| %>
				<div>
					<%= user.username %>
				</div>
			<% end %>
		</div>
	<div class="col-sm-10">
		<% @channel.messages.each do |message| %>
			<p><%= message.user.username %>: <%= message.body %></p>
		<% end %>
		<% if current_user.channels.include?(@channel) %>
			<%= form_with model: [@channel, Message.new] do |f| %>
				<div class="form-group">
					<%= f.text_field :body, placeholder: "Напиши что-нибудь...", autocomplete: 'off', class: "form-control", id: "message_content"%>
				</div>
				<div class="form-group">
					<%= f.submit "Отправить" %>
				</div>
			<% end %>
		<% else %>
			<%= link_to "Присоединиться к каналу: #{@channel.name}", channel_channel_user_path(@channel), method: :post, class: "btn btn-custom"%>
		<% end %>
	</div>
</div>