config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :channels do
    resource :channel_user
    resources :messages
  end
  devise_for :users
  ActiveAdmin.routes(self)
  root 'movies#index'
  resources :movies, only: %i[index show] do
    resources :reviews
    member do
      put 'like' => 'movies#upvote'
      put 'dislike' => 'movies#downvote'
    end
  end
  get 'favorite/:id' => 'favorites#show', as: 'favorite'
  delete 'favorite/:id' => 'favorites#destroy'
  post 'line_items' => 'line_items#create'
  get 'line_items/:id' => 'line_items#show', as: 'line_item'
  delete 'line_items/:id' => 'line_items#destroy'
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  require 'net/http'
  before_action :set_movie, only: %i[show upvote downvote]

  def index
    if params[:category].blank? && params[:search].blank?
      @movies = Movie.all.page(params[:page]).per(10)
    elsif params[:search].present?
      search = params[:search]
      movies = Movie.where('title_ru LIKE ? OR title_ru LIKE ? OR lower(title_en) LIKE ?',
                           "%#{search.capitalize}%", "%#{search.downcase}%", "%#{search.downcase}%")
      @movies = movies.page(params[:page]).per(10)
    else
      @category = Category.find(params[:category])
      @movies = @category.movies.page(params[:page]).per(10)
    end

    @session = VoterSession.find_by(session_id: request.session_options[:id].to_s)
    @session = VoterSession.create(session_id: request.session_options[:id].to_s) if @session.nil?

    @categories = Category.all
  end

  def show
    set_rendom_movies
    @review = Review.new
  end

  def upvote
    @session = VoterSession.find_by(session_id: request.session_options[:id].to_s)
    @session = VoterSession.create(session_id: request.session_options[:id].to_s) if @session.nil?
    @movie.upvote_by @session
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { render json: { count: @movie.liked_count } }
      format.js   { render layout: false }
    end
  end

  def downvote
    @session = VoterSession.find_by(session_id: request.session_options[:id].to_s)
    @session = VoterSession.create(session_id: request.session_options[:id].to_s) if @session.nil?
    @movie.downvote_by @session
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { render json: { count: @movie.disliked_count } }
      format.js   { render layout: false }
    end
  end

  def set_rendom_movies
    @recommendation = []
    i = 0 # category iteration in array
    redo_count = 0
    7.times do
      i = 0 if i > @movie.categories.size - 1
      begin
        random_movie = Movie.find(@movie.categories[i].movies.pluck(:id).sample)
      rescue NoMethodError => e
        random_movie = Movie.find(Movie.pluck(:id).sample)
      end
      if @recommendation.include?(random_movie) || (random_movie == @movie)
        if redo_count <= 7
          redo_count += 1
          redo
        else
          break
        end
      else
        @recommendation << random_movie
      end
      i += 1
    end
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def genre_link(movie)
    valid_genre = movie.categories.map do |genre_object|
      link_to(genre_object.genre.to_s, movies_path(category: genre_object))
    end
    no_valid_genre = movie.genre.split(', ') - movie.categories.map { |genre_object| genre_object.genre }
    (valid_genre + no_valid_genre).join(', ').html_safe
  end
end

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_votes.html.erb
<div class="caption">
  <%= link_to like_movie_path(movie), class: "like", id: "like-#{movie.id}", method: :put, remote: true do %>
      <button type="button" class="btn btn-success btn-up-background" aria-label="Left Align">
      <span class="fa fa-thumbs-up" aria-hidden="true"></span>
      <span class="badge" id="up-<%= movie.id %>"><%= movie.get_upvotes.size + movie.like %></span>
    </button>
  <% end %>

  <%= link_to dislike_movie_path(movie), class: "like", id: "dislike-#{movie.id}", method: :put , remote: true do %>
      <button type="button" class="btn btn-danger btn-down-background" aria-label="Left Align">
      <span class="fa fa-thumbs-down" aria-hidden="true"></span>
      <span class="badge" id="down-<%= movie.id %>"><%= movie.get_downvotes.size + movie.dislike %></span>
    </button>
  <% end %>
</div>

app/views/movies/downvote.js.erb
$('#dislike-<%= @movie.id %>').bind('ajax:success', function() {
   $('#down-<%= @movie.id %>').html('<%=escape_javascript (@movie.get_downvotes.size + @movie.dislike).to_s %>');
   $('#up-<%= @movie.id %>').html('<%=escape_javascript (@movie.get_upvotes.size + @movie.like).to_s %>');
});

app/views/movies/index.html.erb
<div class="row">
  <div class="col-sm-5 col-md-4 col-lg-3 col-xl-3">
    <div class="movie-card">
      <h2>По жанру:</h2>
      <div class="list-group">
        <% @categories.each do|category| %>
          <%= link_to category.genre.capitalize, movies_path(category: category), class: "list" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-sm-7 col-md-8 col-lg-9 col-xl-9">
    <% @movies.each do |movie| %>
     <div class="row movie-card">
      <div class="col-lg-4">

        <div>
          <%= image_tag("#{movie.image_link}", width: "100%")%>
          <%= render partial: 'movies/votes', :locals => {:movie => movie, :session => @session} %>
        </div>
      </div>
        <div class="col-lg-8"> 
          <div class="row">
            <div class="col-sm-10 col-md-10 col-lg-10 col-xl-10">
              <div class="movie_title index-title">
                <h2><%=link_to "#{movie.title_ru}", movie_path(movie), class:"title-link"%></h2>
                <h5><%= movie.title_en %></h5>
              </div>
            </div>
            <div class="col-sm-2 col-md-2 col-lg-2 col-xl-2 bookmark-conteiner">

              <% if favorite_include_movie?(movie) %>
                <%= link_to "", line_item_path(movie), method: :delete, class: "fa fa-minus bookmark link-danger" %>
               <% else %>
                <%= link_to "", line_items_path(movie_id: movie), method: :post, class: "fa fa-plus bookmark link-succes" %>
               <% end %>
            </div>
          </div>
          <table class="movie-info">
            <tbody>
              <tr class="index-th-mh">
                <th scope="row">Страна:</th>
                <td><%= movie.country %></td>
              </tr>
              <tr>
                <th scope="row">Жанр:</th>
                <td><%= genre_link(movie) %></td>
              </tr>
              <% if movie.duration.present? %>
                <tr>
                  <th scope="row">Продолжительность:</th>
                  <td><%= movie.duration%> мин. / <%=Time.at(movie.duration.to_i*60).utc.strftime("%H:%M")%></td>
                </tr>
              <% end %>
              <tr>
                <th scope="row">Год:</th>
                <td><%= movie.year %></td>
              </tr>
            </tbody>
          </table>
          <p class="index_description"><%= movie.description %></p>
        </div>
      </div>
      <hr>
    <% end %>
    <div class="pagination-conteiner">
      <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12">
          <%= paginate @movies, outer_window: 3 %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/movies/show.html.erb
<div class="row">
  <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
    <div class="movie_title show-title">
      <h1><%= @movie.title_ru %></h1>
      <h5><%= @movie.title_en %></h5>
    </div>
  </div>
</div>

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-5 col-xl-4">
      <div class="show-poster">
        <%= image_tag("#{@movie.image_link}",width: "100%", alt: "#{@movie.title_en}")%>
      </div>
    </div>
  <div class="col-sm-12 col-md-12 col-lg-7 col-xl-8">
    <table class="movie-info">
      <tbody>
        <tr>
          <th scope="row">Страна:</th>
          <td><%= @movie.country %></td>
        </tr>
        <tr>
          <th scope="row">Жанр:</th>
          <td><%= genre_link(@movie) %></td>
        </tr>
        <tr>
          <th scope="row">Год:</th>
          <td><%= @movie.year %></td>
        </tr>
        <% unless @movie.producer.nil? %>
          <tr>
            <th scope="row">Режиссёр:</th>
            <td><%= @movie.producer %></td>
          </tr>
        <% end %>
        <% unless @movie.acter.empty? %>
          <tr>
            <th scope="row">В главной роли:</th>
            <td><%= @movie.acter %></td>
          </tr>
        <% end %>
        <% if @movie.duration.present? %>
          <tr>
            <th scope="row">Продолжительность:</th>
            <td class="td2"><%=@movie.duration%> мин. / <%=Time.at(@movie.duration.to_i*60).utc.strftime("%H:%M")%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <hr>
    <p><%= @movie.description %></p>
  </div>
</div>

<div class="row">
  <div class="col-sm-12 col-md-12 col-lg-5 col-xl-4">
    <h3>Советуем посмотреть:</h3>
    <% @recommendation.each do |movie| %>
    <ul class="recommend-ul">
      <li class=recommend-li>
      <%= link_to "#{movie.title_ru} (#{movie.year} г.)", movie_path(movie) %>
    </li>
    </ul>
    <% end %>

  </div>
  <div class="col-sm-12 col-md-12 col-lg-7 col-xl-8">
    <div class="bkg-videoplayer">
      <iframe src="https://63.tvmovies.in/PwUgndLBDUPr?kp_id=<%=@movie.global_id%>" width="640" height="480" frameborder="0" allowfullscreen class="videoplayer"></iframe>
    </div>
    <div class="review">
      <h2>Отзывы:</h2>
      <% @movie.reviews.each do |review| %>
        <h5 class="review-user"><%= review.user.username %>:</h5>
        <p class="review-body"><%= review.body %></p>
      <% end %>
      <% if user_signed_in? %>
        <%= form_with model: [@movie, @review] do |f|%>

        <% if @review.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@review.errors.count, "error") %> prohibited this movie from being saved:</h2>

            <ul>
            <% @review.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>


          <div class="form-group">
            <%= f.text_area :body, placeholder: "Оставить комментарий", autocomplete: 'off', class: "form-control"%>
          </div>
          <div class="form-group">
            <%= f.submit "Отправить" %>
          </div>
        <% end %>
        <% else %>
          <p><%= link_to "Войдите", new_user_session_path %>, чтобы оставить комментарий. </p>
      <% end %>
    </div>
  </div>
</div>

app/views/movies/upvote.js.erb
$('#like-<%= @movie.id %>').bind('ajax:success', function() {
   $('#up-<%= @movie.id %>').html('<%=escape_javascript (@movie.get_upvotes.size + @movie.like).to_s %>');
   $('#down-<%= @movie.id %>').html('<%=escape_javascript (@movie.get_downvotes.size + @movie.dislike).to_s %>');

  $('#like-<%= @movie.id %>').show();


});