config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :channels do
    resource :channel_user
    resources :messages
  end
  devise_for :users
  ActiveAdmin.routes(self)
  root 'movies#index'
  resources :movies, only: %i[index show] do
    resources :reviews
    member do
      put 'like' => 'movies#upvote'
      put 'dislike' => 'movies#downvote'
    end
  end
  get 'favorite/:id' => 'favorites#show', as: 'favorite'
  delete 'favorite/:id' => 'favorites#destroy'
  post 'line_items' => 'line_items#create'
  get 'line_items/:id' => 'line_items#show', as: 'line_item'
  delete 'line_items/:id' => 'line_items#destroy'
end

app/controllers/reviews_controller.rb
class ReviewsController < InheritedResources::Base
  before_action :set_movie
  before_action :authenticate_user!

  def create
    @review = @movie.reviews.build(review_params)
    @review.user = current_user
    respond_to do |format|
      if @review.save
        format.html { redirect_to request.referrer, notice: 'Комментарий успешно создан.' }
      else
        format.html { redirect_to movie_path(@movie), alert: 'Комментарий не был создан.' }
      end
    end
  end

  private

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:body)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= simple_form_for(@review) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.association :movie %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Movie</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.user %></td>
        <td><%= review.movie %></td>
        <td><%= review.body %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @review.user %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @review.movie %>
</p>

<p>
  <strong>Body:</strong>
  <%= @review.body %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>