config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :channels do
    resource :channel_user
    resources :messages
  end
  devise_for :users
  ActiveAdmin.routes(self)
  root 'movies#index'
  resources :movies, only: %i[index show] do
    resources :reviews
    member do
      put 'like' => 'movies#upvote'
      put 'dislike' => 'movies#downvote'
    end
  end
  get 'favorite/:id' => 'favorites#show', as: 'favorite'
  delete 'favorite/:id' => 'favorites#destroy'
  post 'line_items' => 'line_items#create'
  get 'line_items/:id' => 'line_items#show', as: 'line_item'
  delete 'line_items/:id' => 'line_items#destroy'
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, msg| %>
 <% if key == "notice" %>
    <div class="alert alert-info" id="flash"><%= msg %></div>
    <% elsif key == "alert" || key == "danger" %>
    	<div class="alert alert-danger" id="flash"><%= msg %></div>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ddm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Arimo" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Russo+One" rel="stylesheet">
  </head>

  <body>
     <header>
      <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark rounded">
          <%=link_to "DDM", root_path, class:"navbar-brand" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
            <span class="fa fa-bars"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarsExample09">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <%= link_to "Закладки (#{@favorite.line_items.count})", favorite_path(@favorite), class:"nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Чат киноманов", channels_path, class:"nav-link" %>
              </li>
            </ul>
            <%= render 'search/form' %>
             <% if user_signed_in? %>
                <span class="navbar-brand navbar-username"><%= current_user.username%></span>
                  <span class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown"></a>
                        <ul class="dropdown-menu customdrop customnav">
                          <li><%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></li>
                          <li><%= link_to 'Изменить профиль', edit_user_registration_path %> </li>
                          <% if current_user.admin %>
                            <li><%= link_to 'Панель админа', admin_root_path %>
                          <% end %>
                        </ul>
                    </span>
                <% else %>
                    <span class="dropdown customnav navbar-username">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Вход <b class="caret"></b></a>
                        <ul class="dropdown-menu customdrop customnav">
                            <li><%= link_to 'Войти', new_user_session_path %> </li>
                            <li><%= link_to 'Зарегистрироваться', new_user_registration_path %></li>
                        </ul>
                    </span>
                <% end %>
          </div>
        </nav>
      </div>
    </header>
    <div class="container custom-container">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
  </body>
</html>